name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Geologica
      fonts:
        - asset: fonts/Geologica_Auto-Black.ttf
        - asset: fonts/Geologica_Auto-Regular.ttf
        - asset: fonts/Geologica_Auto-Light.ttf
        - asset: fonts/Geologica_Auto-Thin.ttf
        - asset: fonts/Geologica_Auto-Medium.ttf
